"""Initial Migration

Revision ID: 85e06eadc3b7
Revises: c9c1fd842349
Create Date: 2020-05-10 16:30:15.738782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e06eadc3b7'
down_revision = 'c9c1fd842349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('posted', sa.DateTime(), nullable=True))
    op.add_column('blogs', sa.Column('subtitle', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'subtitle')
    op.drop_column('blogs', 'posted')
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
