"""Initial Migration

Revision ID: cbc782031dd9
Revises: 85e06eadc3b7
Create Date: 2020-05-10 18:45:28.982755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc782031dd9'
down_revision = '85e06eadc3b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('mycontent', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('mysubtitle', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('mytitle', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'content')
    op.drop_column('blogs', 'subtitle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('subtitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'mytitle')
    op.drop_column('blogs', 'mysubtitle')
    op.drop_column('blogs', 'mycontent')
    # ### end Alembic commands ###
